server.port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: ssh://git@bitbucket.subatomic.local:30999/tp/test-configuration.git
          searchPaths: '{application}'
          refreshRate: 0 # Change this to refresh every X seconds
  cache:
    type: none

logging.level.org.springframework:
  context.annotation: warn
  cloud.config.server: warn    
