server.port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: ssh://git@bitbucket.subatomic.local:30999/tp/test-configuration.git
          searchPaths: '{application}'
  cache:
    type: none
